version: '3.2'

services:
  gitlab:
    restart: always
#    hostname: 'gitlab.example.com'
    build: ./gitlab
    env_file: .env
    ports:
      - "10122:22"
      - "10180:80"
      #- "10443:443"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    environment:
      #- GITLAB_OMNIBUS_CONFIG="external_url='http://elara.syh.socionext.com:10180';"
      - DEBUG=false
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=localhost
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - GITLAB_ROOT_PASSWORD=testtest
      - GITLAB_ROOT_EMAIL=okazaki.yuji@socionext.com

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=okazaki.yuji@socionext.com
      - GITLAB_EMAIL_REPLY_TO=okazaki.yuji@socionext.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=okazaki.yuji@socionext.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00


volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  jenkins-data2:
  redmine-files:
  redmine-db-data:

