version: '2'
services:
  jenkins:
    build:
      context: .
    hostname: jenkins
    env_file: .env
    ports:
      - "8088:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw
    restart: always
